// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0vH0GonuwSsqr36MQWKTgWTjTzEcCC5A',
    appId: '1:1059099479328:web:fca7e14cca233331e71b45',
    messagingSenderId: '1059099479328',
    projectId: 'shop060p',
    authDomain: 'shop060p.firebaseapp.com',
    storageBucket: 'shop060p.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAitgRS2h8DlUroNvkYvrxxCH4N2g62Mfc',
    appId: '1:1059099479328:android:d3a58320d6b2fd3fe71b45',
    messagingSenderId: '1059099479328',
    projectId: 'shop060p',
    storageBucket: 'shop060p.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnwpbRitiSiMA1oYdiKVm0dh25_ZG8cX4',
    appId: '1:1059099479328:ios:67e444ea6a9fa874e71b45',
    messagingSenderId: '1059099479328',
    projectId: 'shop060p',
    storageBucket: 'shop060p.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );
}
